baseURL = 'https://zzmblog.top/'
languageCode = 'zh-CN'
title = '张芷铭的个人博客'
theme = ''

# Exclude certain directories from build
excludeFiles = [
  'fluent_python_example_code/**',
  '**/*.adoc',
  '**/*.asciidoc',
]

[params]
  description = "基于 Hugo 和 Obsidian 的个人博客"
  dateFormat = "2006-01-02"

  # Obsidian 特性
  enableWikilinks = true
  enableBacklinks = true
  enableGraph = true

  [params.author]
    name = "Benjamin"
    email = "zzm_ai@bupt.edu.cn"

[taxonomies]
  tag = 'tags'
  category = 'categories'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # 允许 HTML
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        heading = true
        title = true
  [markup.asciidocExt]
    enabled = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
  [markup.highlight]
    style = 'monokai'
    lineNos = true

[outputs]
  home = ['HTML', 'RSS', 'JSON']
  page = ['HTML']
  section = ['HTML', 'RSS']

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    name = "搜索"
    url = "/search/"
    weight = 4
  [[menu.main]]
    name = "知识图谱"
    url = "/graph/"
    weight = 5

[security]
  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^npx$', '^postcss$', '^asciidoctor$', '^rst2html(\.py)?$']
